platform :ios, '8.0'

target 'JCChartProject' do
use_frameworks!
pod 'AFNetworking','~> 3.0'
pod 'MJExtension'
pod 'lottie-ios','~>1.5.0'
pod 'MBProgressHUD'
pod 'MJRefresh','~> 2.5.0'
pod 'SDWebImage'
end
